# Generated by Django 2.2.7 on 2019-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20191114_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=50)),
                ('activityNum', models.CharField(max_length=50)),
                ('activityOwner', models.CharField(max_length=50)),
                ('activityScore', models.CharField(max_length=50)),
                ('activityPoster', models.ImageField(default='', upload_to='img/<django.db.models.fields.CharField>')),
                ('activityDescribe', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TakePartIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityNum', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
                ('openID', models.CharField(max_length=50)),
                ('userScore', models.CharField(max_length=50)),
                ('userMail', models.CharField(max_length=50)),
                ('userPhone', models.CharField(max_length=50)),
                ('userZhiYuanBJ', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
