# Generated by Django 2.2.7 on 2019-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20191121_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinfo',
            name='activityPoster',
            field=models.ImageField(upload_to='img'),
        ),
    ]
