# Generated by Django 2.2.7 on 2019-11-28 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=50)),
                ('activityNum', models.CharField(max_length=50)),
                ('activityOwner', models.CharField(max_length=50)),
                ('activityScore', models.CharField(max_length=50)),
                ('activityPoster', models.ImageField(default=0, upload_to='media')),
                ('activityDescribe', models.TextField(max_length=1000)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('activityContact', models.ImageField(default=0, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityNum', models.CharField(max_length=50)),
                ('messageContent', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('groupID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TakePartIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityNum', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
                ('department', models.CharField(default='', max_length=50)),
                ('openID', models.CharField(max_length=50)),
                ('userScore', models.CharField(max_length=50)),
                ('userMail', models.CharField(max_length=50)),
                ('userPhone', models.CharField(max_length=50)),
                ('userZhiYuanBJ', models.CharField(max_length=50)),
                ('hasNewMessage', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
