# Generated by Django 2.2.5 on 2019-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takepartin',
            old_name='userID',
            new_name='openID',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userInterest',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userIntro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userSex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
