# Generated by Django 2.2.5 on 2019-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0002_auto_20191203_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takepartin',
            old_name='openID',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='activityinfo',
            name='activityStatus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activityinfo',
            name='peopleCurrent',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='activityinfo',
            name='peopleNeed',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='activitymessage',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userInterest',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userIntro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userSex',
            field=models.CharField(max_length=10),
        ),
    ]
