# Generated by Django 2.2.5 on 2019-12-12 09:12

from django.db import migrations, models
import wechatAPP.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0005_auto_20191205_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinfo',
            name='activityAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activityinfo',
            name='activityType',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='activityContact',
            field=models.ImageField(default=0, upload_to=wechatAPP.models.activity_directory_path),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='activityPoster',
            field=models.ImageField(default=0, upload_to=wechatAPP.models.activity_directory_path),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='peopleCurrent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='peopleNeed',
            field=models.IntegerField(default=0),
        ),
    ]
