# Generated by Django 2.2.5 on 2019-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0006_auto_20191212_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinfo',
            name='signInQrcode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activityinfo',
            name='signOffQrcode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='takepartin',
            name='endTime',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='takepartin',
            name='startTime',
            field=models.CharField(default='', max_length=50),
        ),
    ]
