# Generated by Django 2.2.5 on 2019-12-15 07:02

from django.db import migrations, models
import wechatAPP.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0008_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='groupHead',
            field=models.ImageField(default=0, upload_to=wechatAPP.models.group_directory_path),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='groupIntro',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='groupPwd',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
