# Generated by Django 2.2.5 on 2019-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0009_auto_20191215_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='sessionID',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
