# Generated by Django 2.2.5 on 2019-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatAPP', '0010_administrator_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='takepartin',
            name='manHours',
            field=models.CharField(default='', max_length=50),
        ),
    ]
